account/urls.py
from django.urls import path
from .views import ArticleListView, ArticleCreate, HomeView, ArticleUpdate, ArticleDelete, Profile

app_name = "account"
urlpatterns = [

    path('', HomeView.as_view(), name='home'), # صفحه شخصی

    path('articles/', ArticleListView.as_view(), name='listArticle'), # نمایش لیست مقالات

    path('article/create/', ArticleCreate.as_view(), name='articleCreate'), # ایجاد مقاله
    path('article/update/<int:pk>/', ArticleUpdate.as_view(), name='articleUpdate'), # ویرایش مقاله
    path('article/delete/<int:pk>/', ArticleDelete.as_view(), name='articleDelete'), # حذف مقاله
    
    path('profile/', Profile.as_view(), name='profile'), # مشخصات حساب

]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from account.views import Login, Register, activate

admin.autodiscover()
urlpatterns = [

    path('', include('pages.urls')),
    path('', include('django.contrib.auth.urls')),
    path('login/', Login.as_view(), name='login'),
    path('register/', Register.as_view(), name='register'),
    path('activate/<uidb64>/<token>', activate, name='activate'),
    path('account/', include('account.urls')),
    path('admin/', admin.site.urls),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . views import (
    detailArticle,
    templateHomeView,
    articleListView,
    templateAboutView,
    categoryView,
    CategoryListView,
    userView,
    previewArticle,
)

app_name = "pages"
urlpatterns = [
    
    path('', templateHomeView.as_view(), name = "homePosts"), # صفحه اصلی سایت
    path('about/', templateAboutView.as_view(), name = "about"), 

    path('category/', categoryView.as_view(), name = "category"), # نمایش دسته بندی ها
    path('category/page/<int:page>', categoryView.as_view(), name = "category"), # نمایش دسته بندی ها

    path('category/<slug:slug>', CategoryListView.as_view(), name = "categoryList"), # نمایش مقالات یک دسته بندی
    path('category/<slug:slug>/page/<int:page>', CategoryListView.as_view(), name = "categoryList"), # نمایش مقالات یک دسته بندی

    path('user/<slug:username>/', userView.as_view(), name = "user"), # مقالات یک کاربر
    path('user/<slug:username>/page/<int:page>/', userView.as_view(), name = "user"), # مقالات یک کاربر
    
    path('articles/', articleListView.as_view(), name = "listArticles"), # نمایش مقالات
    path('articles/page/<int:page>', articleListView.as_view(), name = "listArticles"), # نمایش مقالات

    path('articles/<slug:slug>/', detailArticle.as_view(), name = "detailArticle"), # توضیحات هر مقاله
    path('preview/<int:pk>/', previewArticle.as_view(), name = "previewArticle"), # نمایش مقاله(منتشر نشده)
]

pages/templates/base.html
{% load static %}
{% load base_tags %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}عنوان صفحه{% endblock %}</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'pages/assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'pages/css/rtl.css' %}" rel="stylesheet" />
        <link href="{% static 'pages/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->

        {% include "navbar.html" %}

        <!-- Masthead-->
        <header class="masthead">
            <div class="container">
                <div class="masthead-heading text-uppercase">{% block heading_title %}وبلاگ جنگویی{% endblock %}</div>
                <!-- <div class="masthead-subheading">خوش آمدید</div> -->
            </div>
        </header>
        <!-- Services-->

        <!-- Portfolio Grid-->
        <section class="page-section bg-light" id="portfolio">
            <div class="container">
                <div class="text-center">
                    <h2 class="section-heading text-uppercase">{% block content_title %}کالا ها{% endblock %}</h2>
                </div>
                {% block content %}
                {% endblock %}
            </div>
        </section>
        <!-- About-->
      
        <!-- Team-->
        <section class="page-section bg-light" id="team">
            <div class="container">
                <div class="text-center">
                    <h2 class="section-heading text-uppercase">تیم ما</h2>
                </div>
                
                {% block team %}
                    <div class="row">
                        <div class="col-lg-4">
                            <div class="team-member">
                                    <img class="mx-auto rounded-circle" src="{% static 'pages/assets/img/team/1.jpg' %}" alt="..." />
                                    <h4>Parveen Anand</h4>
                                    <p class="text-muted">Lead Designer</p>
                                    <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-twitter"></i></a>
                                    <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-facebook-f"></i></a>
                                    <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-linkedin-in"></i></a>
                                </div>
                            </div>
                            <div class="col-lg-4">
                            <div class="team-member">
                                <img class="mx-auto rounded-circle" src="{% static 'pages/assets/img/team/2.jpg' %}" alt="..." />
                                <h4>Diana Petersen</h4>
                                <p class="text-muted">Lead Marketer</p>
                                <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-twitter"></i></a>
                                <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-facebook-f"></i></a>
                                <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-linkedin-in"></i></a>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="team-member">
                                <img class="mx-auto rounded-circle" src="{% static 'pages/assets/img/team/3.jpg' %}" alt="..." />
                                <h4>Larry Parker</h4>
                                <p class="text-muted">Lead Developer</p>
                                <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-twitter"></i></a>
                                <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-facebook-f"></i></a>
                                <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-linkedin-in"></i></a>
                            </div>
                        </div>
                    </div>

                {% endblock %}
            </div>
        </section>
        <!-- Clients-->

        <!-- Contact-->
        <section class="page-section" id="contact">
            <div class="container">
                <div class="text-center">
                    <h2 class="section-heading text-uppercase">ارتباط با ما</h2>
                    <!-- <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3> -->
                </div>
                <!-- * * * * * * * * * * * * * * *-->
                <!-- * * SB Forms Contact Form * *-->
                <!-- * * * * * * * * * * * * * * *-->
                <!-- This form is pre-integrated with SB Forms.-->
                <!-- To make this form functional, sign up at-->
                <!-- https://startbootstrap.com/solution/contact-forms-->
                <!-- to get an API token!-->
                <form id="contactForm" data-sb-form-api-token="API_TOKEN">
                    <div class="row align-items-stretch mb-5">
                        <div class="col-md-6">
                            <div class="form-group">
                                <!-- Name input-->
                                <input class="form-control" id="name" type="text" placeholder="نام *" data-sb-validations="required" />
                                <div class="invalid-feedback" data-sb-feedback="name:required">نام اجباری است</div>
                            </div>
                            <div class="form-group">
                                <!-- Email address input-->
                                <input class="form-control" id="email" type="email" placeholder="ایمیل *" data-sb-validations="required,email" />
                                <div class="invalid-feedback" data-sb-feedback="email:required">ایمیل اجباری است</div>
                                <div class="invalid-feedback" data-sb-feedback="email:email">ایمیل صحیح نمی باشد</div>
                            </div>
                            <div class="form-group mb-md-0">
                                <!-- Phone number input-->
                                <input class="form-control" id="phone" type="tel" placeholder="شماره تلفن *" data-sb-validations="required" />
                                <div class="invalid-feedback" data-sb-feedback="phone:required">شماره تلفن اجباری است</div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group form-group-textarea mb-md-0">
                                <!-- Message input-->
                                <textarea class="form-control" id="message" placeholder="پیام خود را بنویسید*" data-sb-validations="required"></textarea>
                                <div class="invalid-feedback" data-sb-feedback="message:required">پیام اجباری است</div>
                            </div>
                        </div>
                    </div>
                    <!-- Submit success message-->
                    <!---->
                    <!-- This is what your users will see when the form-->
                    <!-- has successfully submitted-->
                    <div class="d-none" id="submitSuccessMessage">
                        <div class="text-center text-white mb-3">
                            <div class="fw-bolder">Form submission successful!</div>
                            To activate this form, sign up at
                            <br />
                            <a href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>
                        </div>
                    </div>
                    <!-- Submit error message-->
                    <!---->
                    <!-- This is what your users will see when there is-->
                    <!-- an error submitting the form-->
                    <div class="d-none" id="submitErrorMessage"><div class="text-center text-danger mb-3">ارسال پیام با خطا مواجه شد</div></div>
                    <!-- Submit Button-->
                    <div class="text-center"><button class="btn btn-primary btn-xl text-uppercase disabled" id="submitButton" type="submit">ارسال پیام</button></div>
                </form>
            </div>
        </section>
        <!-- Footer-->
        <footer class="footer py-4">
            وبلاگ جنگویی
        </footer>
        <!-- Portfolio Modals-->
        <!-- Portfolio item 1 modal popup-->
        
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'pages/js/scripts.js' %}"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

pages/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand" href="{% url 'account:home' %}">ورود</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars ms-1"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
                <li class="nav-item"><a class="nav-link" href="{% url 'pages:listArticles' %}">اجناس</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'pages:category' %}">دسته بندی ها</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'pages:homePosts' %}">خانه</a></li>
            </ul>
        </div>
    </div>
</nav>