myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from account.views import Login, Register, activate

admin.autodiscover()
urlpatterns = [

    path('', include('pages.urls')),
    path('', include('django.contrib.auth.urls')),
    path('login/', Login.as_view(), name='login'),
    path('register/', Register.as_view(), name='register'),
    path('activate/<uidb64>/<token>', activate, name='activate'),
    path('account/', include('account.urls')),
    path('admin/', admin.site.urls),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . views import (
    detailArticle,
    templateHomeView,
    articleListView,
    templateAboutView,
    categoryView,
    CategoryListView,
    userView,
    previewArticle,
)

app_name = "pages"
urlpatterns = [
    
    path('', templateHomeView.as_view(), name = "homePosts"), # صفحه اصلی سایت
    path('about/', templateAboutView.as_view(), name = "about"), 

    path('category/', categoryView.as_view(), name = "category"), # نمایش دسته بندی ها
    path('category/page/<int:page>', categoryView.as_view(), name = "category"), # نمایش دسته بندی ها

    path('category/<slug:slug>', CategoryListView.as_view(), name = "categoryList"), # نمایش مقالات یک دسته بندی
    path('category/<slug:slug>/page/<int:page>', CategoryListView.as_view(), name = "categoryList"), # نمایش مقالات یک دسته بندی

    path('user/<slug:username>/', userView.as_view(), name = "user"), # مقالات یک کاربر
    path('user/<slug:username>/page/<int:page>/', userView.as_view(), name = "user"), # مقالات یک کاربر
    
    path('articles/', articleListView.as_view(), name = "listArticles"), # نمایش مقالات
    path('articles/page/<int:page>', articleListView.as_view(), name = "listArticles"), # نمایش مقالات

    path('articles/<slug:slug>/', detailArticle.as_view(), name = "detailArticle"), # توضیحات هر مقاله
    path('preview/<int:pk>/', previewArticle.as_view(), name = "previewArticle"), # نمایش مقاله(منتشر نشده)
]

pages/templates/pages/CategoryListView.html
{% extends 'pages/list.html' %}
{% load static %}

{% block title %}{{category.title}}{% endblock title %}
{% block content_title %}دسته بندی:{{category.title}}{% endblock content_title %}

{% block product %}

    <div class="col-lg-4 col-sm-6 mb-4">
        <div class="portfolio-item">
            <img class="img-fluid" src="{{ obj.thumbnail.url }}" alt="{{ obj.title }}" />
            <div class="portfolio-caption">
                <a href="{% url 'pages:detailArticle' obj.slug %}"><div class="portfolio-caption-heading">{{obj.title}}</div></a>
                <a href="{% url 'pages:user' obj.author %}">#{{obj.author}}</a>
                <div class="portfolio-caption-subheading text-muted">{{obj.description|striptags|truncatewords:"20"}}</div>
            </div>
        </div>
    </div>

{% endblock %}

{% block page_previous %}
    <a class="btn btn-primary float-rigth ml-3" href="{% url 'pages:categoryList' category.slug page_obj.previous_page_number %}"> نمایش پست های قدیمی تر &larr;</a>      
{% endblock %}
{% block page_next %}
    <a class="btn btn-primary float-rigth ml-3" href="{% url 'pages:categoryList' category.slug page_obj.next_page_number %}"> نمایش پست های جدید تر &rarr;</a>  
{% endblock %}

pages/templates/pages/about.html
{% extends 'base.html' %}

{% block content %}
    about django
{% endblock content %}

pages/templates/pages/category.html
{% extends 'pages/list.html' %}
{% load static %}

{% block title %}list Category{% endblock title %}
{% block content_title %}دسته بندی{% endblock content_title %}

{% block product %}

    <div class="col-lg-4 col-sm-6 mb-4">
        <div class="portfolio-item">
            <div class="portfolio-caption">
                <a href="{% url 'pages:categoryList' obj.slug %}"><div class="portfolio-caption-heading">{{obj.title}}</div></a>
            </div>
        </div>
    </div>

{% endblock %}

{% block page_previous %}
    <a class="btn btn-primary float-rigth ml-3" href="{% url 'pages:category' page_obj.previous_page_number %}"> نمایش دسته بندی های قدیمی تر &larr;</a>  
{% endblock %}

{% block page_next %}
    <a class="btn btn-primary float-rigth ml-3" href="{% url 'pages:category' page_obj.next_page_number %}"> نمایش دسته بندی های جدید تر &rarr;</a>  
{% endblock %}

pages/templates/pages/detailArticle.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{article.slug}}{% endblock title %}

{% block content_title %}
    {{article.title}}
    {% if article.is_special %}
        <span class="badge" style="background-color: rgb(231, 49, 49); font-size: 13px;">ویژه </span>
    {% endif %}  
{% endblock content_title %}

{% block heading_title %} {{article.title}} {% endblock heading_title %}

{% block content %}

    {% if object.is_special %}
        
        {% if user.is_authenticated and user.is_special_user or user == object.author or user.is_superuser %}
            <h1>{{article.id}}) {{article.title}}</h1>
            <img src="{{ article.thumbnail.url }}" alt="{{ article.title }}" width="300" height="200">
            <p>{{article.description|safe|linebreaks}}</p>
            <small>{{article.publish}}</small>
            <br>
            <a href="#">#{{article.author}}</a>
    
        {% else %}
            <p>{{article.description|safe|linebreaks}}</p>
            <p class="alert alert-warning">این مقاله ویژه است و برای مشاهده آن باید <a href="#">کاربر ویژه</a> باشید.</p>
        {% endif %}
        
    {% else %}
        <h1>{{article.id}}) {{article.title}}</h1>
        <img src="{{ article.thumbnail.url }}" alt="{{ article.title }}" width="300" height="200">
        <p>{{article.description|safe|linebreaks}}</p>
        <small>{{article.jpublish}}</small>
        <br>
        <a href="{% url 'pages:user' article.author %}">#{{article.author}}</a>
    {% endif %}
    
{% endblock %}

pages/templates/pages/home.html
{% extends 'base.html' %}

{% block title %}home{% endblock title %}
{% block content_title %}خانه{% endblock %}

pages/templates/pages/list.html
{% extends 'base.html' %}

{% block content %}

{% if object_list %}
    <div class="row">

    {% for obj in object_list %}

        {% block product %}{% endblock %}
    
    {% endfor %}

    </div>

{% else %}

    not found

{% endif %}

<br><br><br><br>

<div class="clearfix pager-botton">

    {% if page_obj.has_previous %}
        {% block page_previous %}{% endblock %}
        <br>
    {% endif %}   
 
    {% if page_obj.has_next %}
        {% block page_next %}{% endblock %}
        <br>
    {% endif %}   

</div>

{% endblock content %}

pages/templates/pages/listArticle.html
{% extends 'pages/list.html' %}
{% load static %}

{% block title %}لیست مقالات{% endblock title %}
{% block content_title %}کالاها-{{page_obj.number}}{% endblock content_title %}

{% block product %}

    <div class="col-sm-4 mb-4">
        <div class="portfolio-item">
            <img class="img-fluid" src="{{ obj.thumbnail.url }}" alt="{{ obj.title }}" />
            <div class="portfolio-caption">
                <a href="{% url 'pages:detailArticle' obj.slug %}">
                    <div class="portfolio-caption-heading">{{obj.title}}</a> 
                        {% if obj.is_special %}
                            <span class="badge" style="background-color: rgb(231, 49, 49); font-size: 13px;">ویژه </span>
                        {% endif %}  
                    </div>
                <a href="{% url 'pages:user' obj.author %}">#{{obj.author}}</a>
                <div class="portfolio-caption-subheading text-muted">{{obj.description|striptags|truncatewords:"20"}}</div>
            </div>
        </div>
    </div>
    
{% endblock %}

{% block page_previous %}
    <a class="btn btn-primary float-rigth ml-3" href="{% url 'pages:listArticles' page_obj.previous_page_number %}"> نمایش پست های قدیمی تر &larr;</a>      
{% endblock %}
{% block page_next %}
    <a class="btn btn-primary float-rigth ml-3" href="{% url 'pages:listArticles' page_obj.next_page_number %}"> نمایش پست های جدید تر &rarr;</a>  
{% endblock %}

pages/templates/pages/user.html
{% extends 'pages/list.html' %}

{% block title %}list Article{% endblock title %}
{% block content_title %}
کالاها-{{page_obj.number}}
{% endblock content_title %}


{% block product %}

    <div class="col-sm-4 mb-4">
        <div class="portfolio-item">
            <img class="img-fluid" src="{{ obj.thumbnail.url }}" alt="{{ obj.title }}" />
            <div class="portfolio-caption">
                <a href="{% url 'pages:detailArticle' obj.slug %}">
                    <div class="portfolio-caption-heading">{{obj.title}}</a> 
                        {% if obj.is_special %}
                            <span class="badge" style="background-color: rgb(231, 49, 49); font-size: 13px;">ویژه </span>
                        {% endif %}  
                    </div>
                <a href="#">#{{obj.author}}</a>
                <div class="portfolio-caption-subheading text-muted">{{obj.description|striptags|truncatewords:"20"}}</div>
            </div>
        </div>
    </div>

{% endblock %}

{% block page_previous %}
    <a class="btn btn-primary float-rigth ml-3" href="{% url 'pages:user' author.username page_obj.previous_page_number %}"> نمایش پست های قدیمی تر &larr;</a>      
{% endblock %}
{% block page_next %}
    <a class="btn btn-primary float-rigth ml-3" href="{% url 'pages:user' author.username page_obj.next_page_number %}"> نمایش پست های جدید تر &rarr;</a>  
{% endblock %}